
import json
import os
from pathlib import Path

from dotenv import load_dotenv
from web3 import Web3




PROJECT_ROOT = Path(__file__).resolve().parents[2]

BLOCKCHAIN_DIR = PROJECT_ROOT / "blockchain"

ENV_PATH = BLOCKCHAIN_DIR / ".env"

load_dotenv(ENV_PATH)


# ============================================================
# 2. CONFIGURATION
# ============================================================

RPC_URL = os.getenv("RPC_URL")
PRIVATE_KEY = os.getenv("PRIVATE_KEY")

# Your currently deployed FreelanceEscrow contract
ESCROW_ADDRESS = "0x9AF814D18DD67B09CceA594d54f625fd63D0B870"

# Hardhat artifact generated after:
# npx hardhat compile
ARTIFACT_PATH = (
    BLOCKCHAIN_DIR
    / "artifacts"
    / "contracts"
    / "FreelanceEscrow.sol"
    / "FreelanceEscrow.json"
)


# ============================================================
# 3. BASIC CONFIGURATION CHECK
# ============================================================

if not RPC_URL:
    raise ValueError(
        "RPC_URL not found in blockchain/.env"
    )

if not PRIVATE_KEY:
    raise ValueError(
        "PRIVATE_KEY not found in blockchain/.env"
    )


# ============================================================
# 4. LOAD CONTRACT ABI
# ============================================================

def load_contract_abi():
    """
    Load FreelanceEscrow ABI generated by Hardhat.
    """

    if not ARTIFACT_PATH.exists():
        raise FileNotFoundError(
            f"Contract artifact not found:\n{ARTIFACT_PATH}\n\n"
            "Run this command first:\n"
            "npx hardhat compile"
        )

    with open(ARTIFACT_PATH, "r", encoding="utf-8") as file:
        artifact = json.load(file)

    return artifact["abi"]


# ============================================================
# 5. CONNECT TO POLYGON AMOY
# ============================================================

def get_web3():
    """
    Connect to Polygon Amoy.
    """

    w3 = Web3(Web3.HTTPProvider(RPC_URL))

    if not w3.is_connected():
        raise ConnectionError(
            f"Could not connect to Polygon Amoy.\nRPC: {RPC_URL}"
        )

    return w3


# ============================================================
# 6. GET ORACLE ACCOUNT
# ============================================================

def get_oracle_account(w3):
    """
    Derive the wallet address from PRIVATE_KEY.
    """

    account = w3.eth.account.from_key(PRIVATE_KEY)

    return account


# ============================================================
# 7. REPORT AI SCORE TO BLOCKCHAIN
# ============================================================

def report_score_to_blockchain(job_id: int, ai_score: int):
    """
    Send AI compliance score to FreelanceEscrow.

    Parameters
    ----------
    job_id : int
        Job ID created on the blockchain.

    ai_score : int
        AI compliance score from 0 to 100.

    Returns
    -------
    dict
        Transaction result.
    """

    # --------------------------------------------------------
    # Validate score
    # --------------------------------------------------------

    if not isinstance(ai_score, (int, float)):
        return {
            "success": False,
            "error": "AI score must be a number."
        }

    ai_score = int(round(ai_score))

    if ai_score < 0 or ai_score > 100:
        return {
            "success": False,
            "error": f"AI score must be between 0 and 100. Got {ai_score}"
        }

    if job_id < 0:
        return {
            "success": False,
            "error": "Job ID cannot be negative."
        }

    try:

        # ----------------------------------------------------
        # Connect
        # ----------------------------------------------------

        w3 = get_web3()

        print("Connected to Polygon Amoy")
        print("Chain ID:", w3.eth.chain_id)

        # ----------------------------------------------------
        # Oracle account
        # ----------------------------------------------------

        account = get_oracle_account(w3)

        print("Oracle address:", account.address)

        # ----------------------------------------------------
        # Check wallet balance
        # ----------------------------------------------------

        balance = w3.eth.get_balance(account.address)

        balance_pol = w3.from_wei(balance, "ether")

        print("Oracle balance:", balance_pol, "POL")

        if balance == 0:

            return {
                "success": False,
                "error": "Oracle wallet has no POL for gas."
            }

        # ----------------------------------------------------
        # Load ABI
        # ----------------------------------------------------

        abi = load_contract_abi()

        # ----------------------------------------------------
        # Create contract instance
        # ----------------------------------------------------

        contract = w3.eth.contract(
            address=Web3.to_checksum_address(
                ESCROW_ADDRESS
            ),
            abi=abi
        )

        # ----------------------------------------------------
        # Verify score oracle
        # ----------------------------------------------------

        configured_oracle = contract.functions.scoreOracle().call()

        print(
            "Contract scoreOracle:",
            configured_oracle
        )

        if configured_oracle.lower() != account.address.lower():

            return {
                "success": False,
                "error": (
                    "Oracle wallet mismatch!\n"
                    f"Wallet: {account.address}\n"
                    f"Contract oracle: {configured_oracle}"
                )
            }

        # ----------------------------------------------------
        # Check job
        # ----------------------------------------------------

        job = contract.functions.getJob(job_id).call()

        print("Job ID:", job_id)
        print("Job status:", job[-1])

        # ----------------------------------------------------
        # Build transaction
        # ----------------------------------------------------

        nonce = w3.eth.get_transaction_count(
            account.address,
            "pending"
        )

        gas_price = w3.eth.gas_price

        transaction = contract.functions.recordScore(
            job_id,
            ai_score
        ).build_transaction({

            "from": account.address,

            "nonce": nonce,

            "gas": 300000,

            "gasPrice": gas_price,

            "chainId": w3.eth.chain_id
        })

        # ----------------------------------------------------
        # Sign transaction
        # ----------------------------------------------------

        signed_transaction = account.sign_transaction(
            transaction
        )

        # ----------------------------------------------------
        # Send transaction
        # ----------------------------------------------------

        tx_hash = w3.eth.send_raw_transaction(
            signed_transaction.raw_transaction
        )

        tx_hash_hex = tx_hash.hex()

        print("Transaction sent:")
        print(tx_hash_hex)

        # ----------------------------------------------------
        # Wait for confirmation
        # ----------------------------------------------------

        print("Waiting for confirmation...")

        receipt = w3.eth.wait_for_transaction_receipt(
            tx_hash,
            timeout=120
        )

        # ----------------------------------------------------
        # Result
        # ----------------------------------------------------

        success = receipt.status == 1

        result = {

            "success": success,

            "tx_hash": tx_hash_hex,

            "job_id": job_id,

            "score_reported": ai_score,

            "gas_used": receipt.gasUsed,

            "block_number": receipt.blockNumber,

            "oracle_address": account.address,

            "explorer_url":
                f"https://amoy.polygonscan.com/tx/{tx_hash_hex}"
        }

        return result

    except Exception as error:

        return {
            "success": False,
            "error": str(error)
        }


# ============================================================
# 8. TEST
# ============================================================

if __name__ == "__main__":

    print("=" * 60)
    print("TRUSTLANCE ORACLE BRIDGE")
    print("=" * 60)

    print()
    print("ENV file:")
    print(ENV_PATH)

    print()
    print("Escrow contract:")
    print(ESCROW_ADDRESS)

    print()

    # IMPORTANT:
    #
    # Do NOT use job_id=1 unless job 1 actually exists
    # and is currently in Submitted state.
    #
    # This is only a demonstration.
    #

    TEST_JOB_ID = 4
    TEST_AI_SCORE = 87

    result = report_score_to_blockchain(
        job_id=TEST_JOB_ID,
        ai_score=TEST_AI_SCORE
    )

    print()
    print("=" * 60)
    print("RESULT")
    print("=" * 60)

    print(json.dumps(result, indent=4))

    if result.get("success"):

        print()
        print("SUCCESS!")
        print(
            "View transaction:"
        )
        print(
            result["explorer_url"]
        )

    else:

        print()
        print("FAILED")
        print(
            result.get("error")
        )